# Generated by Django 4.2 on 2023-06-02 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='onWatchList', to=settings.AUTH_USER_MODEL),
        ),
    ]
